name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip wget python3-setuptools
          python -m pip install --upgrade pip
          pip install buildozer cython gdown

      - name: Install OpenJDK 17
        run: |
          sudo apt install -y openjdk-17-jdk

      - name: Install Android SDK Command Line Tools and Accept Licenses
        run: |
          # Download Android command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/Android
          rm commandlinetools.zip

          # Set up Android SDK environment
          echo "export ANDROID_HOME=$HOME/Android" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3:$PATH" >> $GITHUB_ENV

          # Accept all SDK licenses interactively
          echo "y" | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
          $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "build-tools;30.0.3" "ndk;21.3.6528147" "tools" "platforms;android-30"

      - name: Download ffmpeg.exe
        run: |
          gdown --id 1t6u5fsMOIlW3XodLp_bjOV60XzXQsiar -O ffmpeg.exe

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
