name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip wget python3-distutils
          python -m pip install --upgrade pip
          pip install buildozer cython gdown

      - name: Install Android SDK & NDK
        run: |
          sudo apt install -y openjdk-17-jdk
          sudo apt install -y android-sdk android-sdk-platform-tools android-sdk-build-tools
          echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Download ffmpeg.exe
        run: |
          gdown --id 1t6u5fsMOIlW3XodLp_bjOV60XzXQsiar -O ffmpeg.exe

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
